{{- if .Values.portal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tenxdev.fullname" . }}-portal
  labels:
    {{- include "tenxdev.portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.portal.service.type }}
  ports:
    - port: {{ .Values.portal.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tenxdev.portal.selectorLabels" . | nindent 4 }}
{{- end }}
