{{- if .Values.documents.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tenxdev.fullname" . }}-documents
  labels:
    {{- include "tenxdev.documents.labels" . | nindent 4 }}
spec:
  type: {{ .Values.documents.service.type }}
  ports:
    - port: {{ .Values.documents.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tenxdev.documents.selectorLabels" . | nindent 4 }}
{{- end }}
