{{- if .Values.notifications.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tenxdev.fullname" . }}-notifications
  labels:
    {{- include "tenxdev.notifications.labels" . | nindent 4 }}
spec:
  type: {{ .Values.notifications.service.type }}
  ports:
    - port: {{ .Values.notifications.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tenxdev.notifications.selectorLabels" . | nindent 4 }}
{{- end }}
